/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYROODOUBLECBSHAPE
#define MYROODOUBLECBSHAPE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyRooDoubleCBShape : public RooAbsPdf {
public:
  MyRooDoubleCBShape() {} ; 
  MyRooDoubleCBShape(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _width,
	      RooAbsReal& _alpha1,
	      RooAbsReal& _n1,
	      RooAbsReal& _alpha2,
	      RooAbsReal& _n2);
  MyRooDoubleCBShape(const MyRooDoubleCBShape& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyRooDoubleCBShape(*this,newname); }
  inline virtual ~MyRooDoubleCBShape() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy width ;
  RooRealProxy alpha1 ;
  RooRealProxy n1 ;
  RooRealProxy alpha2 ;
  RooRealProxy n2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MyRooDoubleCBShape,1) // Your description goes here...
};
 
#endif
